/* ── BAKALAVR data ─────────────────────────────────────────── */
export const BAKALAVR = [
  {
    name: "Maktabgacha ta'lim",
    price: 12850000,
    duration: '4 yil',
    lang: "O'zbek / Rus",
    studyForm: 'Kunduzgi',
    icon: 'users',
    // ✅ TO'G'RI: 6-belgili hex rang
    color: '#1c2cb9',
    desc: `Maktabgacha yoshdagi bolalar bilan ishlash bo'yicha yuqori malakali mutaxassislar tayyorlash. Bolalar psixologiyasi va pedagogikasi asosida professional kadrlar.`,
    subjects: ['Psixologiya', 'Pedagogika', 'Bolalar adabiyoti', 'Matematika asoslari', 'Musiqa', 'Jismoniy tarbiya'],
    career: ["Maktabgacha ta'lim muassasasi direktori", 'Tarbiyachi', 'Metodist', 'Psixolog', "Bolalar bog'chasi rahbari"],
  },
  {
    name: "Boshlang'ich ta'lim",
    price: 12850000,
    duration: '4 yil',
    lang: "O'zbek",
    studyForm: 'Kunduzgi',
    icon: 'book',
    // ✅ FIX 1: '#3abd31fa' → '#3abd31'
    // Muammo: 8-belgili hex (#RRGGBBAA) ishlatilgan edi.
    // ${f.color}25 => '#3abd31fa25' — bu noto'g'ri CSS, border ko'rinmagan.
    color: '#3abd31',
    desc: "Boshlang'ich sinf o'quvchilariga ta'lim beruvchi malakali o'qituvchilar tayyorlash. Zamonaviy pedagogik usullar va innovatsion ta'lim texnologiyalari.",
    subjects: ['Ona tili', 'Matematika', 'Tabiat', "Tasviriy san'at", 'Musiqa', 'Pedagogika asoslari'],
    career: ["Boshlang'ich sinf o'qituvchisi", 'Metodist', 'Maktab direktori', "Ta'lim menejeri"],
  },
  {
    name: "Milliy g'oya, ma'naviyat asoslari va huquqta'limi",
    price: 12850000,
    duration: '4 yil',
    lang: "O'zbek",
    studyForm: 'Kunduzgi',
    icon: 'home',
    color: '#d7690f',
    desc: "Milliy qadriyatlar, huquq va ma'naviyat sohasida bilimli, vatanparvar mutaxassislar tayyorlash. Huquqiy ong va fuqarolik tarbiyasiga yo'naltirilgan dastur.",
    subjects: ['Konstitutsiyaviy huquq', "Milliy g'oya", 'Falsafa', 'Tarix', 'Huquqshunoslik', "Ma'naviyat asoslari"],
    career: ["O'qituvchi", 'Davlat xizmati mutaxassisi', 'Huquqiy maslahatchi', "Ma'naviyat targ'ibotchisi"],
  },
  {
    name: 'Neft va gaz ishi',
    price: 12850000,
    duration: '4 yil',
    lang: "O'zbek / Ingliz",
    studyForm: 'Kunduzgi',
    icon: 'map',
    color: '#e3dd2c',
    desc: "Neft-gaz sanoati uchun yuqori malakali muhandis va texnologlar tayyorlash. Faoliyat turlari bo'yicha ixtisoslashish imkoniyati mavjud.",
    subjects: ['Neft kimyosi', 'Qazib olish texnologiyasi', 'Ekologiya', 'Iqtisodiyot', 'Muhandislik', 'Geologiya'],
    career: ['Neft-gaz muhandisi', 'Texnolog', 'Laborant', 'Loyiha menejeri', 'Ekolog-mutaxassis'],
    note: "Faoliyat turlari bo'yicha ixtisoslashish mavjud",
  },
  {
    name: 'Iqtisodiyot',
    price: 14900000,
    duration: '4 yil',
    lang: "O'zbek / Ingliz",
    studyForm: 'Kunduzgi',
    icon: 'dollar',
    color: '#059669',
    desc: "Zamonaviy bozor iqtisodiyoti sharoitida raqobatbardosh iqtisodchilar tayyorlash. Tarmoqlar va sohalar bo'yicha ixtisoslashish imkoniyati mavjud.",
    subjects: ['Makroiqtisodiyot', 'Mikroiqtisodiyot', 'Marketing', 'Menejment', 'Statistika', 'Raqamli iqtisodiyot'],
    career: ['Iqtisodchi', 'Moliyaviy tahlilchi', 'Bank xodimi', 'Tadbirkor', 'Davlat boshqaruvi mutaxassisi'],
    note: "Tarmoqlar va sohalar bo'yicha ixtisoslashish mavjud",
  },
  {
    name: 'Dasturiy injiniring',
    price: 12850000,
    duration: '4 yil',
    lang: "O'zbek / Ingliz",
    studyForm: 'Kunduzgi',
    icon: 'code',
    color: '#06bdc7',
    desc: "Zamonaviy dasturiy ta'minot ishlab chiqish sohasida yuqori malakali mutaxassislar tayyorlash. Sun'iy intellekt, veb va mobil dasturlash.",
    subjects: ['Python', 'JavaScript', "Ma'lumotlar bazasi", "Sun'iy intellekt", 'Mobil dasturlash', 'Kiberxavfsizlik'],
    career: ['Dasturchi', 'Web developer', 'Data scientist', 'DevOps', 'IT menejeri', 'Kiberxavfsizlik mutaxassisi'],
  },
  {
    name: 'Moliya va moliyaviy texnologiyalar',
    price: 14900000,
    duration: '4 yil',
    lang: "O'zbek / Ingliz",
    studyForm: 'Kunduzgi',
    icon: 'briefcase',
    color: '#793bac',
    desc: "FinTech va zamonaviy moliya sohasida innovatsion mutaxassislar tayyorlash. Blokcheyn, raqamli bankchilik va investitsiya texnologiyalari.",
    subjects: ['Moliya nazariyasi', 'Blokcheyn', 'FinTech', 'Risk menejment', 'Investitsiya', 'Kriptovalyuta'],
    career: ['Moliyaviy maslahatchi', 'FinTech mutaxassisi', 'Bank xodimi', 'Investitsiya menejeri', 'Risk-menejer'],
  },
  {
    name: 'Buxgalteriya hisobi',
    price: 14900000,
    duration: '4 yil',
    lang: "O'zbek",
    studyForm: 'Kunduzgi',
    icon: 'file',
    color: '#f33218',
    desc: "Moliyaviy hisobot, audit va soliq sohasida malakali buxgalterlar tayyorlash. IFRS xalqaro standartlari asosida o'qitish.",
    subjects: ['Buxgalteriya hisobi', 'Audit', 'Soliqlar', 'Moliyaviy tahlil', '1C dasturi', 'IFRS standartlari'],
    career: ['Buxgalter', 'Auditor', 'Moliyaviy direktor', 'Soliq maslahatchi', 'IFRS mutaxassisi'],
  },
  {
    name: 'Psixologiya',
    price: 12850000,
    duration: '4 yil',
    lang: "O'zbek",
    studyForm: 'Kunduzgi',
    icon: 'hex',
    color: '#db2777',
    desc: "Insonlar ruhiy salomatligi va ijtimoiy muammolarini hal qiluvchi psixologlar tayyorlash. Faoliyat turlari bo'yicha ixtisoslashish imkoniyati mavjud.",
    subjects: ['Umumiy psixologiya', 'Klinik psixologiya', 'Ijtimoiy psixologiya', 'Psixodiagnostika', 'Nevrologiya asoslari'],
    career: ['Psixolog', 'Psixoterapevt', 'HR mutaxassisi', 'Klinik psixolog', 'Ijtimoiy ishchi'],
    note: "Faoliyat turlari bo'yicha ixtisoslashish mavjud",
  },
  {
    name: "Filologiya va tillarni o'qitish",
    price: 12850000,
    duration: '4 yil',
    lang: "O'zbek / Ingliz / Rus",
    studyForm: 'Kunduzgi',
    icon: 'globe',
    color: '#29a6f8',
    desc: "Til va adabiyot sohasida bilimli, xalqaro miqyosda faoliyat yurita oladigan mutaxassislar tayyorlash. Uch yo'nalish: Ingliz, O'zbek va Rus tili.",
    subjects: ['Ingliz tili', 'Adabiyot', 'Tilshunoslik', 'Tarjima nazariyasi', 'Nutq madaniyati', "O'zbek tili"],
    career: ["O'qituvchi", 'Tarjimon', 'Muharrir', 'Diplomat', 'Jurnalist'],
    note: "Yo'nalishlar: Ingliz tili | O'zbek tili | Rus tili",
  },
]

/* ── MAGISTRATURA data ─────────────────────────────────────── */
export const MAGISTRATURA = [
  {
    name: 'Lingvistika (Ingliz tili)',
    price: 18000000,
    duration: '2 yil',
    lang: "O'zbek / Ingliz",
    studyForm: 'Kunduzgi',
    icon: 'globe',
    color: '#2563eb',
    desc: "Ingliz tili lingvistikasi sohasida ilmiy-tadqiqot va pedagogik faoliyat olib boruvchi yuqori malakali mutaxassislar tayyorlash. Xalqaro ilmiy hamkorlik imkoniyatlari.",
    subjects: ['Ingliz tilshunoslik nazariyasi', 'Qiyosiy tilshunoslik', 'Ilmiy tadqiqot metodologiyasi', 'Tarjima nazariyasi', 'Lingvokulturologiya', 'Diskurs tahlili'],
    career: ["Oliy o'quv yurti o'qituvchisi", 'Ilmiy tadqiqotchi', 'Tarjimon', 'Lingvistika mutaxassisi', 'Xalqaro tashkilot mutaxassisi'],
  },
  {
    name: 'Lingvistika (Rus tili)',
    price: 18000000,
    duration: '2 yil',
    lang: "O'zbek / Rus",
    studyForm: 'Kunduzgi',
    icon: 'book',
    color: '#ae0895',
    desc: "Rus tili lingvistikasi sohasida ilmiy-tadqiqot va pedagogik faoliyatga tayyorlangan chuqur bilimli mutaxassislar yetishtirish. Kognitiv va qiyosiy tilshunoslik.",
    subjects: ['Rus tilshunoslik nazariyasi', 'Qiyosiy grammatika', 'Ilmiy tadqiqot metodologiyasi', 'Nutq madaniyati', 'Stilistika', 'Kognitiv tilshunoslik'],
    career: ["Oliy o'quv yurti o'qituvchisi", 'Tarjimon', 'Ilmiy tadqiqotchi', 'Muharrir', 'Diplomat'],
  },
  {
    name: 'Iqtisodiyot',
    price: 18000000,
    duration: '2 yil',
    lang: "O'zbek / Ingliz",
    studyForm: 'Kunduzgi',
    icon: 'dollar',
    color: '#416c2a',
    desc: "Iqtisodiy siyosat, tahlil va boshqaruv sohasida chuqur ilmiy bilimga ega mutaxassislar tayyorlash. Xalqaro iqtisodiyot va raqamli iqtisod ixtisoslashuvi.",
    subjects: ['Makroiqtisodiy tahlil', 'Tadqiqot metodologiyasi', 'Raqamli iqtisodiyot', 'Xalqaro iqtisodiyot', 'Iqtisodiy siyosat', 'Ekonometrika'],
    career: ['Iqtisodchi-tahlilchi', 'Davlat boshqaruv mutaxassisi', 'Konsultant', 'Ilmiy tadqiqotchi', 'Xalqaro tashkilotlar mutaxassisi'],
  },
]
